# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Copyright 2024 Ian McIntyre

[package]
name = "fusible-hybrid-app"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
fusible = { workspace = true }

[build-dependencies]
cc = { workspace = true }
