# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Copyright 2024 Ian McIntyre

[package]
name = "fusible-allocator"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
fusible.workspace = true
